#!/usr/bin/env python3
import pandas as pd
import json
import argparse
import os
import sys

# ==========================================
# 🔧 配置区域：在这里定义你的学科映射关系
# ==========================================
BATCH_CONFIG = [
    {
        "input": "math.xlsx", 
        "output": "subjects/math/data.js", 
        "var_name": "MATH_DATA"
    },
    {
        "input": "econ.xlsx", 
        "output": "subjects/econ/data.js", 
        "var_name": "ECON_DATA"
    },
    # 未来只需在这里加一行：
    # { "input": "physics.xlsx", "output": "subjects/physics/data.js", "var_name": "PHYSICS_DATA" },
]
# ==========================================

def generate_data(input_file, output_file, var_name=None):
    # 检查输入文件是否存在
    if not os.path.exists(input_file):
        print(f"⚠️ 跳过: 找不到文件 '{input_file}'")
        return

    print(f"🔄 正在处理: {input_file} -> {output_file} ...")
    
    try:
        df = pd.read_excel(input_file, dtype={'year': str, 'quest#': str, 'quest file': str, 'path': str})
    except Exception as e:
        print(f"❌ 读取失败: {e}")
        return

    df.columns = df.columns.str.strip()
    
    # 如果没有指定 var_name，尝试自动推断
    if not var_name:
        if "econ" in output_file.lower(): var_name = "ECON_DATA"
        elif "phys" in output_file.lower(): var_name = "PHYSICS_DATA"
        else: var_name = "MATH_DATA"

    papers_list = []
    
    # 分组逻辑 (按试卷 qp 分组)
    if 'qp' not in df.columns:
        print(f"❌ 错误: {input_file} 缺少 'qp' 列")
        return

    grouped = df.groupby('qp')
    for qp_name, group in grouped:
        first_row = group.iloc[0]
        paper_obj = {
            "id": qp_name,
            "year": str(first_row['year']),
            "subject": str(first_row['2nd sub']),
            "paperName": f"{qp_name}.pdf".replace(".pdf.pdf", ".pdf").upper(),
            "questions": []
        }
        
        for _, row in group.iterrows():
            q_num = str(row['quest#'])
            q_file = str(row['quest file'])
            base_path = str(row['path'])
            
            # 智能清洗路径：不管 Excel 里写没写 subjects/xxx/，都清洗干净
            clean_path = base_path
            # 移除常见前缀
            prefixes = ["subjects/math/", "subjects/econ/", "subjects/physics/", 
                        "subjects/math", "subjects/econ", "subjects/physics"]
            for p in prefixes:
                clean_path = clean_path.replace(p, "")
            
            if clean_path.startswith("/"): clean_path = clean_path[1:]

            full_url = ""
            title_desc = ""
            
            # 判断是否是新题
            # 假设 Excel 里有一列叫 'new'，如果填了 'y'，就在标题前加个标记
            is_new = str(row.get('new', '')).lower() == 'y'
            
            if q_file != "nan" and q_file.strip() != "":
                if not clean_path.endswith("/"): clean_path += "/"
                full_url = f"{clean_path}{q_file}"
                title_desc = f"Question {q_num}"
            else:
                title_desc = "题目暂未录入"

            q_data = {
                "qNum": q_num,
                "title": title_desc, 
                "url": full_url
            }
            
            # 如果是新题，可以加个标记字段（前端需配合修改才能显示，这里先存数据）
            if is_new:
                q_data["isNew"] = True

            paper_obj["questions"].append(q_data)
            
        papers_list.append(paper_obj)
    
    papers_list.sort(key=lambda x: x['year'], reverse=True)

    js_content = f"// Auto-generated by datagen.py\n// Source: {input_file}\n\nconst {var_name} = "
    js_content += json.dumps(papers_list, indent=4, ensure_ascii=False)
    js_content += ";"

    try:
        # 自动创建输出目录（如果不存在）
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(js_content)
        print(f"✅ 成功! {var_name} 已更新。")
    except Exception as e:
        print(f"❌ 写入失败: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Auto-generate data.js for Respect Quiz")
    parser.add_argument("-i", "--input", help="Input Excel file")
    parser.add_argument("-o", "--output", help="Output JS file")
    
    args = parser.parse_args()
    
    # 逻辑分支：
    if args.input and args.output:
        # 模式 1: 命令行指定了文件，只处理这一个
        generate_data(args.input, args.output)
    else:
        # 模式 2: 没给参数，进入【自动批处理模式】
        print("🚀 开始批量更新所有学科数据...\n")
        for task in BATCH_CONFIG:
            generate_data(task["input"], task["output"], task["var_name"])
        print("\n✨ 所有任务执行完毕!")