#!/usr/bin/env python3
import pandas as pd
import json
import argparse
import os
import sys

def generate_data(input_file, output_file):
    print(f"正在读取 Excel 文件: {input_file} ...")
    
    try:
        # 读取 Excel，强制将某些列作为字符串处理，防止年份变成数字
        df = pd.read_excel(input_file, dtype={
            'year': str, 
            'quest#': str, 
            'quest file': str,
            'path': str
        })
    except FileNotFoundError:
        print(f"❌ 错误: 找不到文件 '{input_file}'")
        sys.exit(1)
    except Exception as e:
        print(f"❌ 读取 Excel 失败: {e}")
        sys.exit(1)

    # 数据清洗：去除列名的空格
    df.columns = df.columns.str.strip()
    
    # 检查必须的列是否存在
    required_columns = ['subject', 'year', '2nd sub', 'qp', 'quest#', 'path']
    for col in required_columns:
        if col not in df.columns:
            print(f"❌ Excel 缺少必要的列: {col}")
            sys.exit(1)

    # 结果列表
    papers_list = []

    # 按试卷 (qp) 分组
    grouped = df.groupby('qp')

    for qp_name, group in grouped:
        # 获取试卷的基本信息（取该组第一行的数据）
        first_row = group.iloc[0]
        
        paper_obj = {
            "id": qp_name,
            "year": str(first_row['year']),
            "subject": str(first_row['2nd sub']),
            # 假设 Excel 里的 qp 只是文件名不含后缀，自动补 .pdf
            # 如果 Excel 里已经有 .pdf，这行代码也没问题，下面的 replace 会处理
            "paperName": f"{qp_name}.pdf".replace(".pdf.pdf", ".pdf").upper(),
            "questions": []
        }

        # 遍历该试卷下的所有题目
        for _, row in group.iterrows():
            q_num = str(row['quest#'])
            q_file = str(row['quest file'])
            base_path = str(row['path'])
            
            # --- 核心逻辑：生成 URL ---
            # 1. 清洗 base_path，我们要的是 index.html (在 subjects/math/) 相对的路径
            # Excel 里的 path 是: subjects/math/2025/M/...
            # 我们需要变成: 2025/M/...
            # 所以把前面的 'subjects/math/' 替换为空
            clean_path = base_path.replace("subjects/math/", "").replace("subjects/math", "")
            if clean_path.startswith("/"):
                clean_path = clean_path[1:]

            # 2. 判断是否有解题文件
            full_url = ""
            title_desc = "" # 默认为空，如果 excel 以后加了 title 列可以读这里

            if q_file != "nan" and q_file.strip() != "":
                # 有文件名，拼接路径
                # 确保路径末尾有 /
                if not clean_path.endswith("/"):
                    clean_path += "/"
                full_url = f"{clean_path}{q_file}"
                # 这里可以自定义有题目时的默认标题
                title_desc = f"Question {q_num}" 
            else:
                # 没有文件名
                title_desc = "题目暂未录入"

            q_obj = {
                "qNum": q_num,
                "title": title_desc, 
                "url": full_url
            }
            
            paper_obj["questions"].append(q_obj)

        # 对题目按题号排序 (可选，防止 Excel 乱序)
        # paper_obj["questions"].sort(key=lambda x: int(x['qNum']) if x['qNum'].isdigit() else 999)

        papers_list.append(paper_obj)

    # 对试卷按年份倒序排列 (新的在前面)
    papers_list.sort(key=lambda x: x['year'], reverse=True)

    # 生成 JS 内容
    js_content = f"// Auto-generated by datagen.py\n// Source: {input_file}\n\nconst MATH_DATA = "
    js_content += json.dumps(papers_list, indent=4, ensure_ascii=False)
    js_content += ";"

    # 写入文件
    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(js_content)
        print(f"✅ 成功! 已生成数据文件: {output_file}")
        print(f"📊 共处理了 {len(papers_list)} 套试卷，包含 {len(df)} 条题目记录。")
    except Exception as e:
        print(f"❌ 写入文件失败: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert Excel to data.js for Respect Quiz")
    parser.add_argument("-i", "--input", default="math.xlsx", help="Input Excel file (default: math.xlsx)")
    parser.add_argument("-o", "--output", default="subjects/math/data.js", help="Output JS file (default: subjects/math/data.js)")
    
    args = parser.parse_args()
    
    generate_data(args.input, args.output)