#!/usr/bin/env python3
import pandas as pd
import json
import argparse
import os
import sys

# ==========================================
# 🔧 配置区域
# ==========================================
BATCH_CONFIG = [
    {
        "key": "math", # 用于命令行匹配的标识
        "input": "math.xlsx", 
        "output": "subjects/math/data.js", 
        "var_name": "MATH_DATA"
    },
    {
        "key": "econ",
        "input": "econ.xlsx", 
        "output": "subjects/econ/data.js", 
        "var_name": "ECON_DATA"
    },
    {
        "key": "phys",
        "input": "physics.xlsx", 
        "output": "subjects/phys/data.js", 
        "var_name": "PHYSICS_DATA" 
    },
]
# ==========================================

def generate_data(input_file, output_file, var_name=None):
    # 检查输入文件是否存在
    if not os.path.exists(input_file):
        print(f"⚠️  跳过: 找不到文件 '{input_file}'")
        return

    print(f"🔄 正在处理: {input_file} -> {output_file} ...")
    
    try:
        df = pd.read_excel(input_file, dtype={'year': str, 'quest#': str, 'quest file': str, 'path': str})
    except Exception as e:
        print(f"❌ 读取失败: {e}")
        return

    df.columns = df.columns.str.strip()
    
    if not var_name:
        if "econ" in output_file.lower(): var_name = "ECON_DATA"
        elif "phys" in output_file.lower(): var_name = "PHYSICS_DATA"
        else: var_name = "MATH_DATA"

    papers_list = []
    
    if 'qp' not in df.columns:
        print(f"❌ 错误: {input_file} 缺少 'qp' 列")
        return

    grouped = df.groupby('qp')
    for qp_name, group in grouped:
        first_row = group.iloc[0]
        paper_obj = {
            "id": qp_name,
            "year": str(first_row['year']),
            "subject": str(first_row['2nd sub']),
            "paperName": f"{qp_name}.pdf".replace(".pdf.pdf", ".pdf").upper(),
            "questions": []
        }
        
        for _, row in group.iterrows():
            q_num = str(row['quest#'])
            q_file = str(row['quest file'])
            base_path = str(row['path'])
            
            clean_path = base_path
            prefixes = ["subjects/math/", "subjects/econ/", "subjects/phys/", 
                        "subjects/math", "subjects/econ", "subjects/phys"]
            for p in prefixes:
                clean_path = clean_path.replace(p, "")
            
            if clean_path.startswith("/"): clean_path = clean_path[1:]

            full_url = ""
            title_desc = ""
            
            is_new = str(row.get('new', '')).lower() == 'y'
            
            if q_file != "nan" and q_file.strip() != "":
                if not clean_path.endswith("/"): clean_path += "/"
                full_url = f"{clean_path}{q_file}"
                title_desc = f"Question {q_num}"
            else:
                title_desc = "题目暂未录入"

            q_data = {
                "qNum": q_num,
                "title": title_desc, 
                "url": full_url
            }
            
            if is_new:
                q_data["isNew"] = True

            paper_obj["questions"].append(q_data)
            
        papers_list.append(paper_obj)
    
    papers_list.sort(key=lambda x: x['year'], reverse=True)

    js_content = f"// Auto-generated by datagen.py\n// Source: {input_file}\n\nconst {var_name} = "
    js_content += json.dumps(papers_list, indent=4, ensure_ascii=False)
    js_content += ";"

    try:
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(js_content)
        print(f"✅ 成功! {var_name} 已更新。\n")
    except Exception as e:
        print(f"❌ 写入失败: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Auto-generate data.js for Respect Quiz")
    
    # 互斥组：要么用 -i/-o 自定义模式，要么用快捷方式模式
    group = parser.add_argument_group('Shortcuts')
    group.add_argument("-m", "--math", action="store_true", help="Update Mathematics only")
    group.add_argument("-e", "--econ", action="store_true", help="Update Economics only")
    group.add_argument("-p", "--phys", action="store_true", help="Update Physics only")
    
    parser.add_argument("-i", "--input", help="Custom Input Excel file")
    parser.add_argument("-o", "--output", help="Custom Output JS file")
    
    args = parser.parse_args()
    
    # 方式二：完全自定义路径模式 (优先级最高)
    if args.input and args.output:
        print(f"🔧 自定义模式: {args.input} -> {args.output}")
        generate_data(args.input, args.output)
        sys.exit(0)

    # 方式三：快捷参数模式
    # 收集用户想要更新的学科 key
    targets = []
    if args.math: targets.append("math")
    if args.econ: targets.append("econ")
    if args.phys: targets.append("phys")

    if targets:
        # 如果用户指定了某些学科，只更新这些
        print(f"🎯 指定更新模式: {', '.join(targets).upper()}\n")
        for task in BATCH_CONFIG:
            if task["key"] in targets:
                generate_data(task["input"], task["output"], task["var_name"])
    else:
        # 方式一：默认模式（什么参数都没加），更新全部
        print("🚀 默认模式：批量更新所有学科...\n")
        for task in BATCH_CONFIG:
            generate_data(task["input"], task["output"], task["var_name"])
        print("✨ 所有任务执行完毕!")