// Auto-generated by datagen.py
// Source: math.xlsx

const MATH_DATA = [
    {
        "id": "qp-202505-mathematics-p43",
        "year": "2025",
        "subject": "M",
        "paperName": "QP-202505-MATHEMATICS-P43.PDF",
        "questions": [
            {
                "qNum": "1",
                "title": "Question 1",
                "url": "2025/M/qp-202505-mathematics-p43/1.html"
            },
            {
                "qNum": "2",
                "title": "Question 2",
                "url": "2025/M/qp-202505-mathematics-p43/2.html"
            },
            {
                "qNum": "3",
                "title": "Question 3",
                "url": "2025/M/qp-202505-mathematics-p43/3.html"
            },
            {
                "qNum": "4",
                "title": "Question 4",
                "url": "2025/M/qp-202505-mathematics-p43/4.html"
            },
            {
                "qNum": "5",
                "title": "Question 5",
                "url": "2025/M/qp-202505-mathematics-p43/5.html"
            },
            {
                "qNum": "6",
                "title": "Question 6",
                "url": "2025/M/qp-202505-mathematics-p43/6.html"
            }
        ]
    },
    {
        "id": "qp-202505-mathematics-p45",
        "year": "2025",
        "subject": "M",
        "paperName": "QP-202505-MATHEMATICS-P45.PDF",
        "questions": [
            {
                "qNum": "1",
                "title": "Question 1",
                "url": "2025/M/qp-202505-mathematics-p45/1.html"
            },
            {
                "qNum": "2",
                "title": "Question 2",
                "url": "2025/M/qp-202505-mathematics-p45/2.html"
            },
            {
                "qNum": "3",
                "title": "Question 3",
                "url": "2025/M/qp-202505-mathematics-p45/3.html"
            },
            {
                "qNum": "4",
                "title": "Question 4",
                "url": "2025/M/qp-202505-mathematics-p45/4.html"
            },
            {
                "qNum": "5",
                "title": "Question 5",
                "url": "2025/M/qp-202505-mathematics-p45/5.html"
            },
            {
                "qNum": "6",
                "title": "Question 6",
                "url": "2025/M/qp-202505-mathematics-p45/6.html"
            },
            {
                "qNum": "7",
                "title": "Question 7",
                "url": "2025/M/qp-202505-mathematics-p45/7.html"
            }
        ]
    },
    {
        "id": "qp-202505-mathematics-p51",
        "year": "2025",
        "subject": "S1",
        "paperName": "QP-202505-MATHEMATICS-P51.PDF",
        "questions": [
            {
                "qNum": "1",
                "title": "题目暂未录入",
                "url": ""
            }
        ]
    }
];