// Auto-generated by datagen.py
// Source: physics.xlsx

const PHYSICS_DATA = [
    {
        "id": "qp-202505-physics-u2",
        "year": "2025",
        "subject": "AS",
        "paperName": "QP-202505-PHYSICS-U2.PDF",
        "questions": [
            {
                "qNum": "1",
                "title": "Question 1",
                "url": "2025/AS/qp-202505-physics-u2/1.html"
            },
            {
                "qNum": "2",
                "title": "Question 2",
                "url": "2025/AS/qp-202505-physics-u2/2.html"
            },
            {
                "qNum": "3",
                "title": "Question 3",
                "url": "2025/AS/qp-202505-physics-u2/3.html"
            },
            {
                "qNum": "4",
                "title": "Question 4",
                "url": "2025/AS/qp-202505-physics-u2/4.html"
            },
            {
                "qNum": "5",
                "title": "Question 5",
                "url": "2025/AS/qp-202505-physics-u2/5.html"
            },
            {
                "qNum": "6",
                "title": "Question 6",
                "url": "2025/AS/qp-202505-physics-u2/6.html"
            },
            {
                "qNum": "7",
                "title": "Question 7",
                "url": "2025/AS/qp-202505-physics-u2/7.html"
            },
            {
                "qNum": "8",
                "title": "Question 8",
                "url": "2025/AS/qp-202505-physics-u2/8.html"
            },
            {
                "qNum": "9",
                "title": "Question 9",
                "url": "2025/AS/qp-202505-physics-u2/9.html"
            },
            {
                "qNum": "10",
                "title": "Question 10",
                "url": "2025/AS/qp-202505-physics-u2/10.html"
            },
            {
                "qNum": "11",
                "title": "Question 11",
                "url": "2025/AS/qp-202505-physics-u2/11.html"
            },
            {
                "qNum": "12-25",
                "title": "Question 12-25",
                "url": "2025/AS/qp-202505-physics-u2/12-25.html"
            }
        ]
    }
];